# ==========================================
# CeciAI - Docker Compose Production
# Configuração adicional para produção
# ==========================================

version: '3.9'

services:
  ceciai:
    environment:
      - ENV=production
      - LOG_LEVEL=WARNING
      - ENABLE_TRADING=true
      - PYTHONOPTIMIZE=2
    
    # Recursos otimizados para produção
    deploy:
      resources:
        limits:
          cpus: '6.0'
          memory: 12G
        reservations:
          cpus: '4.0'
          memory: 8G
      
      # Restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    
    # Logging otimizado
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  ollama:
    # GPU em produção
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  redis:
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru --appendonly yes
    
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
  
  postgres:
    # Backup automático
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backups:/backups
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
